name: Builder

on:
  pull_request:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  dummycloud:
    name: Deye Dummycloud
    uses: ./.github/workflows/build-app.yaml
    with:
      app: dummycloud
      publish: ${{ github.event_name != 'pull_request' }}

  dummycloud2:
    name: Deye Dummycloud v2
    uses: ./.github/workflows/build-app.yaml
    with:
      app: dummycloud2
      publish: ${{ github.event_name != 'pull_request' }}
